// import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBookReader } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <>
      <title>作戦ボード</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />

      <main>
        <div className="flex">
          <div className="title">aa</div>
          <div className="text-4xl">地味に助かる　作戦ボード</div>
          <select class="select" name="" id=""></select>
        </div>
      </main>
    </>
  );
}
